// Comprehensive Country Database for Chrono-Sphere 3D Flag Hourglass
window.CountryData = [
    { code: 'IN', name: 'India', capital: 'New Delhi', continent: 'Asia', timezone: 'Asia/Kolkata', offset: '+05:30', flagColors: ['#FF9933', '#FFFFFF', '#138808', '#000080'] },
    { code: 'US', name: 'United States', capital: 'Washington, D.C.', continent: 'North America', timezone: 'America/New_York', offset: '-04:00', flagColors: ['#B22234', '#FFFFFF', '#3C3B6E'] },
    { code: 'GB', name: 'United Kingdom', capital: 'London', continent: 'Europe', timezone: 'Europe/London', offset: '+01:00', flagColors: ['#00247D', '#CF142B', '#FFFFFF'] },
    { code: 'JP', name: 'Japan', capital: 'Tokyo', continent: 'Asia', timezone: 'Asia/Tokyo', offset: '+09:00', flagColors: ['#FFFFFF', '#BC002D'] },
    { code: 'KR', name: 'South Korea', capital: 'Seoul', continent: 'Asia', timezone: 'Asia/Seoul', offset: '+09:00', flagColors: ['#FFFFFF', '#CD2E3A', '#0047A0', '#000000'] },
    { code: 'DE', name: 'Germany', capital: 'Berlin', continent: 'Europe', timezone: 'Europe/Berlin', offset: '+02:00', flagColors: ['#000000', '#DD0000', '#FFCC00'] },
    { code: 'FR', name: 'France', capital: 'Paris', continent: 'Europe', timezone: 'Europe/Paris', offset: '+02:00', flagColors: ['#002395', '#FFFFFF', '#ED2939'] },
    { code: 'CA', name: 'Canada', capital: 'Ottawa', continent: 'North America', timezone: 'America/Toronto', offset: '-04:00', flagColors: ['#FF0000', '#FFFFFF'] },
    { code: 'AU', name: 'Australia', capital: 'Canberra', continent: 'Oceania', timezone: 'Australia/Sydney', offset: '+10:00', flagColors: ['#00008B', '#FF0000', '#FFFFFF'] },
    { code: 'BR', name: 'Brazil', capital: 'Brasília', continent: 'South America', timezone: 'America/Sao_Paulo', offset: '-03:00', flagColors: ['#009739', '#FEDD00', '#012169'] },
    { code: 'IT', name: 'Italy', capital: 'Rome', continent: 'Europe', timezone: 'Europe/Rome', offset: '+02:00', flagColors: ['#009246', '#FFFFFF', '#CE2B37'] },
    { code: 'ES', name: 'Spain', capital: 'Madrid', continent: 'Europe', timezone: 'Europe/Madrid', offset: '+02:00', flagColors: ['#AA151B', '#F1BF00'] },
    { code: 'MX', name: 'Mexico', capital: 'Mexico City', continent: 'North America', timezone: 'America/Mexico_City', offset: '-05:00', flagColors: ['#006847', '#FFFFFF', '#CE1126'] },
    { code: 'CN', name: 'China', capital: 'Beijing', continent: 'Asia', timezone: 'Asia/Shanghai', offset: '+08:00', flagColors: ['#DE2910', '#FFDE00'] },
    { code: 'ZA', name: 'South Africa', capital: 'Pretoria', continent: 'Africa', timezone: 'Africa/Johannesburg', offset: '+02:00', flagColors: ['#007749', '#FFB81C', '#00205B', '#E03C31', '#FFFFFF', '#000000'] },
    { code: 'AE', name: 'United Arab Emirates', capital: 'Abu Dhabi', continent: 'Asia', timezone: 'Asia/Dubai', offset: '+04:00', flagColors: ['#FF0000', '#007A3D', '#FFFFFF', '#000000'] },
    { code: 'SA', name: 'Saudi Arabia', capital: 'Riyadh', continent: 'Asia', timezone: 'Asia/Riyadh', offset: '+03:00', flagColors: ['#006C35', '#FFFFFF'] },
    { code: 'SG', name: 'Singapore', capital: 'Singapore', continent: 'Asia', timezone: 'Asia/Singapore', offset: '+08:00', flagColors: ['#ED2939', '#FFFFFF'] },
    { code: 'TH', name: 'Thailand', capital: 'Bangkok', continent: 'Asia', timezone: 'Asia/Bangkok', offset: '+07:00', flagColors: ['#A51931', '#F4F5F8', '#2D2A4A'] },
    { code: 'ID', name: 'Indonesia', capital: 'Jakarta', continent: 'Asia', timezone: 'Asia/Jakarta', offset: '+07:00', flagColors: ['#FF0000', '#FFFFFF'] },
    { code: 'MY', name: 'Malaysia', capital: 'Kuala Lumpur', continent: 'Asia', timezone: 'Asia/Kuala_Lumpur', offset: '+08:00', flagColors: ['#010066', '#CC0000', '#FFFFFF', '#FFCC00'] },
    { code: 'VN', name: 'Vietnam', capital: 'Hanoi', continent: 'Asia', timezone: 'Asia/Ho_Chi_Minh', offset: '+07:00', flagColors: ['#DA251D', '#FFFF00'] },
    { code: 'PH', name: 'Philippines', capital: 'Manila', continent: 'Asia', timezone: 'Asia/Manila', offset: '+08:00', flagColors: ['#0038A8', '#CE1126', '#FFFFFF', '#FCD116'] },
    { code: 'TR', name: 'Turkey', capital: 'Ankara', continent: 'Asia/Europe', timezone: 'Europe/Istanbul', offset: '+03:00', flagColors: ['#E30A17', '#FFFFFF'] },
    { code: 'EG', name: 'Egypt', capital: 'Cairo', continent: 'Africa', timezone: 'Africa/Cairo', offset: '+03:00', flagColors: ['#CE1126', '#FFFFFF', '#000000', '#C09300'] },
    { code: 'NG', name: 'Nigeria', capital: 'Abuja', continent: 'Africa', timezone: 'Africa/Lagos', offset: '+01:00', flagColors: ['#008751', '#FFFFFF'] },
    { code: 'AR', name: 'Argentina', capital: 'Buenos Aires', continent: 'South America', timezone: 'America/Argentina/Buenos_Aires', offset: '-03:00', flagColors: ['#74ACDF', '#FFFFFF', '#F6B40E'] },
    { code: 'NL', name: 'Netherlands', capital: 'Amsterdam', continent: 'Europe', timezone: 'Europe/Amsterdam', offset: '+02:00', flagColors: ['#AE1C28', '#FFFFFF', '#21468B'] },
    { code: 'SE', name: 'Sweden', capital: 'Stockholm', continent: 'Europe', timezone: 'Europe/Stockholm', offset: '+02:00', flagColors: ['#006AA7', '#FECC00'] },
    { code: 'CH', name: 'Switzerland', capital: 'Bern', continent: 'Europe', timezone: 'Europe/Zurich', offset: '+02:00', flagColors: ['#FF0000', '#FFFFFF'] },
    { code: 'NZ', name: 'New Zealand', capital: 'Wellington', continent: 'Oceania', timezone: 'Pacific/Auckland', offset: '+12:00', flagColors: ['#00247D', '#CC142B', '#FFFFFF'] },
    { code: 'GR', name: 'Greece', capital: 'Athens', continent: 'Europe', timezone: 'Europe/Athens', offset: '+03:00', flagColors: ['#0D5EAF', '#FFFFFF'] },
    { code: 'PT', name: 'Portugal', capital: 'Lisbon', continent: 'Europe', timezone: 'Europe/Lisbon', offset: '+01:00', flagColors: ['#046A38', '#DA291C', '#FFC72C'] },
    { code: 'IE', name: 'Ireland', capital: 'Dublin', continent: 'Europe', timezone: 'Europe/Dublin', offset: '+01:00', flagColors: ['#169B62', '#FFFFFF', '#FF883E'] },
    { code: 'NO', name: 'Norway', capital: 'Oslo', continent: 'Europe', timezone: 'Europe/Oslo', offset: '+02:00', flagColors: ['#BA0C2F', '#FFFFFF', '#00205B'] },
    { code: 'DK', name: 'Denmark', capital: 'Copenhagen', continent: 'Europe', timezone: 'Europe/Copenhagen', offset: '+02:00', flagColors: ['#C60C30', '#FFFFFF'] },
    { code: 'FI', name: 'Finland', capital: 'Helsinki', continent: 'Europe', timezone: 'Europe/Helsinki', offset: '+03:00', flagColors: ['#FFFFFF', '#002F6C'] },
    { code: 'PL', name: 'Poland', capital: 'Warsaw', continent: 'Europe', timezone: 'Europe/Warsaw', offset: '+02:00', flagColors: ['#FFFFFF', '#DC143C'] },
    { code: 'AT', name: 'Austria', capital: 'Vienna', continent: 'Europe', timezone: 'Europe/Vienna', offset: '+02:00', flagColors: ['#ED2939', '#FFFFFF'] },
    { code: 'BE', name: 'Belgium', capital: 'Brussels', continent: 'Europe', timezone: 'Europe/Brussels', offset: '+02:00', flagColors: ['#000000', '#FDDA24', '#EF3340'] },
    { code: 'KE', name: 'Kenya', capital: 'Nairobi', continent: 'Africa', timezone: 'Africa/Nairobi', offset: '+03:00', flagColors: ['#000000', '#BB0000', '#006600', '#FFFFFF'] },
    { code: 'CL', name: 'Chile', capital: 'Santiago', continent: 'South America', timezone: 'America/Santiago', offset: '-04:00', flagColors: ['#0039A6', '#FFFFFF', '#D52B1E'] },
    { code: 'CO', name: 'Colombia', capital: 'Bogotá', continent: 'South America', timezone: 'America/Bogota', offset: '-05:00', flagColors: ['#FCD116', '#0038A8', '#CE1126'] },
    { code: 'PE', name: 'Peru', capital: 'Lima', continent: 'South America', timezone: 'America/Lima', offset: '-05:00', flagColors: ['#D91023', '#FFFFFF'] },
    { code: 'UA', name: 'Ukraine', capital: 'Kyiv', continent: 'Europe', timezone: 'Europe/Kyiv', offset: '+03:00', flagColors: ['#0057B7', '#FFD700'] }
];
